"""Run a real Ollama-backed end-to-end workflow smoke check."""

from __future__ import annotations

import argparse
import json
import sys
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from src.graph import run_triage_workflow  # noqa: E402
from src.llm import OllamaConfig, OllamaGenerationError, load_ollama_config_from_env  # noqa: E402


def _ollama_url(config: OllamaConfig, path: str) -> str:
    return f"{config.base_url.rstrip('/')}/{path.lstrip('/')}"


def _read_ollama_json(config: OllamaConfig, path: str) -> dict[str, Any]:
    url = _ollama_url(config, path)
    request = urllib.request.Request(url, method="GET")
    with urllib.request.urlopen(request, timeout=min(config.timeout_seconds, 10.0)) as response:
        body = response.read().decode("utf-8")
    data = json.loads(body)
    if not isinstance(data, dict):
        raise RuntimeError(f"Ollama endpoint {url} returned non-object JSON")
    return data


def _model_is_available(config: OllamaConfig) -> bool:
    data = _read_ollama_json(config, "/api/tags")
    models = data.get("models", [])
    if not isinstance(models, list):
        return False

    expected = config.model
    for model in models:
        if not isinstance(model, dict):
            continue
        name = model.get("name")
        if name == expected or name == f"{expected}:latest" or str(name).startswith(f"{expected}:"):
            return True

    return False


def _validate_smoke_output(state, trace_dir: Path) -> list[str]:
    errors: list[str] = []

    if not state.observed_failures:
        errors.append("workflow did not produce observed failures")

    if not state.build_test_findings:
        errors.append("workflow did not produce build/test findings")

    llm_evidence = [
        item for item in state.evidence if item.location == "ollama.semantic_interpretation"
    ]
    if not llm_evidence:
        errors.append("build/test analyzer did not record Ollama interpretation evidence")

    if state.final_report is None:
        errors.append("workflow did not produce a final report")
    else:
        if not state.final_report.executive_summary:
            errors.append("final report is missing the Ollama executive summary")
        if state.final_report.executive_summary == "Autogenerated remediation plan":
            errors.append("final report still contains the deterministic placeholder summary")
        if not state.final_report.recommended_actions:
            errors.append("final report is missing recommended actions")

    trace_file = trace_dir / f"{state.metadata.incident_id}.jsonl"
    if not trace_file.exists():
        errors.append(f"trace file was not written: {trace_file}")
    elif trace_file.stat().st_size == 0:
        errors.append(f"trace file is empty: {trace_file}")

    return errors


def _build_summary(state, trace_dir: Path) -> dict[str, Any]:
    trace_file = trace_dir / f"{state.metadata.incident_id}.jsonl"
    return {
        "incident_id": state.metadata.incident_id,
        "classification": (
            state.final_report.failure_classification.value
            if state.final_report and state.final_report.failure_classification
            else None
        ),
        "observed_failure_count": len(state.observed_failures),
        "build_test_finding_count": len(state.build_test_findings),
        "config_finding_count": len(state.config_findings),
        "llm_interpretation_evidence_count": len(
            [
                item
                for item in state.evidence
                if item.location == "ollama.semantic_interpretation"
            ]
        ),
        "root_cause_summary": (
            state.final_report.root_cause_summary if state.final_report else None
        ),
        "recommended_actions": [
            action.summary for action in state.recommended_actions
        ],
        "trace_file": str(trace_file),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Run a real Ollama-backed end-to-end triage workflow smoke check."
    )
    parser.add_argument(
        "incident_dir",
        nargs="?",
        default=str(REPO_ROOT / "fixtures" / "sample_incidents" / "incident_001"),
        help="Incident directory to analyze.",
    )
    parser.add_argument(
        "--trace-dir",
        default=str(REPO_ROOT / "traces" / "smoke"),
        help="Directory for JSONL trace output.",
    )
    parser.add_argument(
        "--skip-model-check",
        action="store_true",
        help="Skip the /api/tags model availability check before running.",
    )

    args = parser.parse_args(argv)
    incident_dir = Path(args.incident_dir)
    trace_dir = Path(args.trace_dir)
    config = load_ollama_config_from_env()

    if not incident_dir.is_dir():
        print(f"Smoke check failed: incident directory not found: {incident_dir}", file=sys.stderr)
        return 2

    try:
        if not args.skip_model_check and not _model_is_available(config):
            print(
                "Smoke check failed: configured Ollama model is not available. "
                f"Run `ollama pull {config.model}` or set OLLAMA_MODEL.",
                file=sys.stderr,
            )
            return 2

        state = run_triage_workflow(incident_dir, trace_dir=trace_dir)
    except (urllib.error.URLError, TimeoutError, json.JSONDecodeError) as exc:
        print(
            "Smoke check failed: could not reach Ollama at "
            f"{config.base_url} ({exc}). Start Ollama with `ollama serve`.",
            file=sys.stderr,
        )
        return 2
    except OllamaGenerationError as exc:
        print(
            "Smoke check failed: Ollama generation failed "
            f"for model {config.model!r} at {config.base_url}: {exc}",
            file=sys.stderr,
        )
        return 2
    except Exception as exc:
        print(f"Smoke check failed while running workflow: {exc}", file=sys.stderr)
        return 1

    errors = _validate_smoke_output(state, trace_dir)
    if errors:
        print("Smoke check failed:", file=sys.stderr)
        for error in errors:
            print(f"- {error}", file=sys.stderr)
        return 1

    print("Ollama workflow smoke check passed.")
    print(json.dumps(_build_summary(state, trace_dir), indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
