from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from src.state import (
    ConfidenceLevel,
    ConfidenceScore,
    ConfidenceSubjectType,
    FailureCategory,
    FinalReport,
    FindingSeverity,
    RecommendedAction,
    SuspectedCause,
    TriageState,
)


class RemediationPlannerInput(BaseModel):
    model_config = ConfigDict(arbitrary_types_allowed=True)

    state: TriageState


def run_remediation_planner(input_data: RemediationPlannerInput) -> TriageState:
    state = input_data.state.model_copy(deep=True)

    # Simple deterministic planner
    env_findings = [
        f
        for f in (
            state.build_test_findings + state.config_findings + state.dependency_findings
        )
        if f.category == FailureCategory.ENVIRONMENT_ISSUE
    ]

    suspected: list[SuspectedCause] = []
    actions: list[RecommendedAction] = []
    confidences: list[ConfidenceScore] = []

    if env_findings:
        cause = SuspectedCause(
            cause_id="cause-001",
            summary="Missing required environment variables in CI",
            rationale=(
                "Analyzer evidence indicates DATABASE_URL is missing or not configured in CI."
            ),
            related_finding_ids=[f.finding_id for f in env_findings],
            evidence_ids=[],
            confidence=0.9,
            rank=1,
        )
        action = RecommendedAction(
            action_id="action-001",
            summary="Configure required environment variables in CI",
            details=(
                "Add DATABASE_URL to the CI workflow environment or repository secrets."
            ),
            related_cause_ids=[cause.cause_id],
            risk_level=FindingSeverity.LOW,
            confidence=0.9,
            rank=1,
        )
        confidence_score = ConfidenceScore(
            score_id="confidence-001",
            subject_type=ConfidenceSubjectType.CAUSE,
            subject_id=cause.cause_id,
            score=0.9,
            level=ConfidenceLevel.HIGH,
            rationale=(
                "Multiple findings point to a missing CI environment variable."
            ),
            evidence_ids=cause.evidence_ids,
        )

        suspected.append(cause)
        actions.append(action)
        confidences.append(confidence_score)
    else:
        # Generic fallback using first finding if available
        all_findings = (
            state.build_test_findings + state.config_findings + state.dependency_findings
        )
        if all_findings:
            f = all_findings[0]
            cause = SuspectedCause(
                cause_id="cause-001",
                summary=f"Likely root cause related to {f.summary}",
                rationale=f"Based on finding {f.finding_id}",
                related_finding_ids=[f.finding_id],
                evidence_ids=[],
                confidence=0.5,
                rank=1,
            )
            action = RecommendedAction(
                action_id="action-001",
                summary=f"Investigate {f.summary}",
                details=f"Review logs and reproduce the failure: {f.details}",
                related_cause_ids=[cause.cause_id],
                risk_level=FindingSeverity.LOW,
                confidence=0.5,
                rank=1,
            )
            confidence_score = ConfidenceScore(
                score_id="confidence-001",
                subject_type=ConfidenceSubjectType.CAUSE,
                subject_id=cause.cause_id,
                score=0.5,
                level=ConfidenceLevel.MEDIUM,
                rationale="Low-medium confidence for fallback cause",
                evidence_ids=cause.evidence_ids,
            )

            suspected.append(cause)
            actions.append(action)
            confidences.append(confidence_score)

    state.suspected_causes = suspected
    state.recommended_actions = actions
    state.confidence_scores = confidences

    # Final report
    fallback_category = FailureCategory.UNKNOWN
    report = FinalReport(
        incident_id=state.metadata.incident_id,
        failure_classification=(
            FailureCategory.ENVIRONMENT_ISSUE if env_findings else fallback_category
        ),
        executive_summary="Autogenerated remediation plan",
        root_cause_summary=suspected[0].summary if suspected else None,
        recommended_actions=actions,
        evidence_summary=[e.snippet for e in state.evidence[:3]] if state.evidence else [],
        limitations=[
            "Deterministic planner uses heuristic rules and does not modify code."
        ],
    )

    state.final_report = report
    return state


__all__ = ["RemediationPlannerInput", "run_remediation_planner"]
